//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_has_Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_has_Assignment()
        {
            this.Student_gets_Assignment = new HashSet<Student_gets_Assignment>();
        }
    
        public int Course_id { get; set; }
        public int Assignment_id { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_gets_Assignment> Student_gets_Assignment { get; set; }
    }
}
