//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_gets_Assignment
    {
        public int Student_id { get; set; }
        public int Course_id { get; set; }
        public int Assignment_id { get; set; }
        public Nullable<int> oralMark { get; set; }
        public Nullable<int> totalMark { get; set; }
    
        public virtual Course_has_Assignment Course_has_Assignment { get; set; }
        public virtual Student Student { get; set; }
    }
}
